---
title: "514_Data Cleaning"
output: html_document
date: "2024-04-23"
---

```{r}
rm(list=ls())
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(haven)
library(dplyr)
library(tidyverse)
library(epiR)
library(tableone)

data <- read_csv("ACEsdata.csv")

data <- select(data, ASTHMA3, state, X_IMPRACE, SEXVAR, X_AGE_G, X_EDUCAG, X_INCOMG1, ACEDEPRS, ACEDRINK, ACEDRUGS, ACEPRISN, ACEDIVRC, ACEPUNCH, ACEHURT1, ACESWEAR, ACETOUCH, ACETTHEM, ACEHVSEX, ACEADSAF, ACEADNED)

```

```{r}
# Define the list of variables to be converted to NA
na_vars <- c("ASTHMA3", "X_EDUCAG", "X_INCOMG1", 
             "ACEDEPRS", "ACEDRINK", "ACEDRUGS", "ACEPRISN", 
             "ACEDIVRC", "ACEPUNCH", "ACEHURT1", "ACESWEAR", 
             "ACETOUCH", "ACETTHEM", "ACEHVSEX", "ACEADSAF", "ACEADNED")

# Convert "7", "9", and empty strings ("") to NA in selected columns
data <- data %>%
  mutate(across(all_of(na_vars), ~ replace(., . %in% c(7, 9, ""), NA)))

# factor conversions
factor_mappings <- list(
  X_EDUCAG = c("Did not graduate high school", "Graduated high school", 
               "Attended college or technical school", "Graduated from college/technical school"),
  X_INCOMG1 = c("Less than 15,000", "15,000-24,999", "25,000-34,999", 
                "35,000-49,999", "50,000-99,999", "100,000-199,999", "200,000 or more"),
  X_IMPRACE = c("White, Non-Hispanic", "Black, Non-Hispanic", "Asian, Non-Hispanic",
                "American Indian/Alaskan Native, Non-Hispanic", "Hispanic", 
                "Unlisted Race, Non-Hispanic"),
  SEXVAR = c("Male", "Female"),
  ASTHMA3 = c("Yes", "No")
)

data <- data %>%
  mutate(across(names(factor_mappings), ~ factor(., levels = seq_along(factor_mappings[[cur_column()]]), 
                                                 labels = factor_mappings[[cur_column()]])))

# recode age group
#data$X_AGE_G[data$X_AGE_G == 1 | data$X_AGE_G == 2 | data$X_AGE_G == 3] <- 1
#data$X_AGE_G[data$X_AGE_G == 4 | data$X_AGE_G == 5] <- 2
#data$X_AGE_G[data$X_AGE_G == 6] <- 3

# recode age group to have 2 categories
data$X_AGE_G[data$X_AGE_G == 1 | data$X_AGE_G == 2 | data$X_AGE_G == 3] <- 1
data$X_AGE_G[data$X_AGE_G == 4 | data$X_AGE_G == 5 | data$X_AGE_G == 6] <- 2

data$age_group <- factor(data$X_AGE_G,
                   levels = c(1:2),
                   labels = c("18-44","45 or older"))

data$asthma_factor <- factor(data$ASTHMA3,
                             levels = c(1:2),
                             labels = c("Yes","No"))

# check numbers
summary(data$asthma_factor)

#remove rows where ASTHMA3 is NA
data <- data %>% filter(!is.na(ASTHMA3))
summary(data$asthma_factor)
```

```{r}

# dichotomize ACE variables
ace_vars <- c("ACEDEPRS", "ACEDRINK", "ACEDRUGS", "ACEPRISN", "ACEDIVRC")
data <- data %>%
  mutate(across(all_of(ace_vars), ~ factor(., levels = c(1, 2), labels = c("Yes", "No"))))

## for PUNCH, HURT, SWEAR, TOUCH, THEM, HAVESEX: any occurence = YES, never = NO
reverse_vars <- c("ACEPUNCH", "ACEHURT1", "ACESWEAR", "ACETOUCH", "ACETTHEM", "ACEHVSEX")

data <- data %>%
  mutate(across(all_of(reverse_vars), ~ factor(ifelse(. == 1, 2, 1), levels = c(1,2), labels = c("Yes", "No"))))

# for SAFE and NEEDS, anything not "all of the time" will be counted as an ACE

# YES means that they did experience the ACE
data <- data %>%
  mutate(
    ACEADSAF = case_when(ACEADSAF == 5 ~ 2, ACEADSAF %in% c(1,2,3,4) ~ 1, TRUE ~ NA_real_),
    ACE_safe = factor(ACEADSAF, levels = c(1,2), labels = c("Yes", "No")),
    
    ACEADNED = case_when(ACEADNED == 5 ~ 2, ACEADNED %in% c(1,2,3,4) ~ 1, TRUE ~ NA_real_),
    ACE_needs = factor(ACEADNED, levels = c(1,2), labels = c("Yes", "No"))
  )

data <- data %>% filter(!is.na(ASTHMA3))

# Summary checks
summary(data$asthma_factor)
summary(data$ACE_needs)
summary(data$ACE_safe)
summary(data$ACE_havesex)
summary(data$ACE_divorce)

```

```{r}
## TABLE 1

vars <- c("age_group", "sex", "race","education","income","ACE_mentalill","ACE_drink","ACE_drug","ACE_prison","ACE_divorce","ACE_punch","ACE_hurt","ACE_swear","ACE_touch","ACE_them","ACE_havesex","ACE_safe","ACE_needs") 

table1 <- CreateTableOne(vars = vars, data = data, strata = "asthma_factor", includeNA = T)

print(table1)

```

```{r}
## TABLE 2 - UNADJUSTED PRs

# Define the ACE variables
ace_vars <- c("ACE_mentalill", "ACE_drink", "ACE_drug", "ACE_prison", 
              "ACE_divorce", "ACE_punch", "ACE_hurt", "ACE_swear", 
              "ACE_touch", "ACE_them", "ACE_havesex", "ACE_safe", "ACE_needs")

# Initialize a list to store results
pr_results <- list()

# Loop through variables to compute prevalence ratios
for (var in ace_vars) {
  prev_table <- table(data$asthma_factor, data[[var]], deparse.level = 2)
  pr_results[[var]] <- epi.2by2(dat = prev_table, method = "cross.sectional")
}

# Print all results
pr_results

```

```{r}
## TABLE 3 - ADJUSTED PRs

# Is this correct way to adjust for income and education?

strat <- xtabs(~ACE_needs + asthma_factor + sex + age_group, data = data)

#print the cross tabulation you've just created to take a look on your data and understand how it looks like
strat

mh_array <- array(strat,
               dim = c(2,2,4), # this creates a 3 dimension array with n (n = number of categories! in each adjustment variable) tables
               list(exposure = c('Yes', 'No'), # this includes our exposure variable with relevant labels
                    outcomes = c('Yes', 'No'), # this includes our outcome variable with relevant labels
                    confounders = 1:4)) 

# now we use this array with epi.2by2()
epi.2by2(mh_array, method = 'cross.sectional')

```

```{r}
## ANALYZING RACE AS AN EFFECT MODIFER between ACE_mentalill and asthma

strat_White <- xtabs(~ACE_mentalill + asthma_factor + age_group + sex, data = data, subset = race == 'White, Non-Hispanic')
strat_Black <- xtabs(~ACE_mentalill + asthma_factor + age_group + sex, data = data, subset = race == 'Black, Non-Hispanic')
strat_Asian <- xtabs(~ACE_mentalill + asthma_factor + age_group + sex, data = data, subset = race == 'Asian, Non-Hispanic')
strat_AIAN <- xtabs(~ACE_mentalill + asthma_factor + age_group + sex, data = data, subset = race == 'American Indian/Alaskan Native, Non-Hispanic')
strat_Hispanic <- xtabs(~ACE_mentalill + asthma_factor + age_group + sex, data = data, subset = race == 'Hispanic')
strat_Unlisted <- xtabs(~ACE_mentalill + asthma_factor + age_group + sex, data = data, subset = race == 'Unlisted Race, Non-Hispanic')


# print the cross tabulation you've just created to take a look on your data and understand how it looks like
strat_White
strat_Black
strat_Asian # multiple cells too small
strat_AIAN 
strat_Hispanic 
strat_Unlisted

array_White <- array(strat_White,
                 dim = c(2,2,4), 
                 list(exposure = c('Yes', 'No'), 
                      outcomes = c('Yes', 'No'), 
                      confounders = 1:4)) 

array_Black <- array(strat_Black,
                 dim = c(2,2,4), 
                 list(exposure = c('Yes', 'No'), 
                      outcomes = c('Yes', 'No'), 
                      confounders = 1:4)) 

array_AIAN <- array(strat_AIAN,
                 dim = c(2,2,4), 
                 list(exposure = c('Yes', 'No'), 
                      outcomes = c('Yes', 'No'), 
                      confounders = 1:4)) 

array_Hispanic <- array(strat_Hispanic,
                 dim = c(2,2,4), 
                 list(exposure = c('Yes', 'No'), 
                      outcomes = c('Yes', 'No'), 
                      confounders = 1:4)) 

array_Unlisted <- array(strat_Unlisted,
                 dim = c(2,2,4), 
                 list(exposure = c('Yes', 'No'), 
                      outcomes = c('Yes', 'No'), 
                      confounders = 1:4)) 

epi.2by2(array_White, method = 'cross.sectional')
epi.2by2(array_Black, method = 'cross.sectional')
epi.2by2(array_AIAN, method = 'cross.sectional')
epi.2by2(array_Hispanic, method = 'cross.sectional')
epi.2by2(array_Unlisted, method = 'cross.sectional')

```

```{r}
## ANALYZING RACE AS AN EFFECT MODIFER between ACE_havesex and asthma

strat_White <- xtabs(~ACE_havesex + asthma_factor + age_group + sex, data = data, subset = race == 'White, Non-Hispanic')
strat_Black <- xtabs(~ACE_havesex + asthma_factor + age_group + sex, data = data, subset = race == 'Black, Non-Hispanic')
strat_Asian <- xtabs(~ACE_havesex + asthma_factor + age_group + sex, data = data, subset = race == 'Asian, Non-Hispanic')
strat_AIAN <- xtabs(~ACE_havesex + asthma_factor + age_group + sex, data = data, subset = race == 'American Indian/Alaskan Native, Non-Hispanic')
strat_Hispanic <- xtabs(~ACE_havesex + asthma_factor + age_group + sex, data = data, subset = race == 'Hispanic')
strat_Unlisted <- xtabs(~ACE_havesex + asthma_factor + age_group + sex, data = data, subset = race == 'Unlisted Race, Non-Hispanic')

# print the cross tabulation you've just created to take a look on your data and understand how it looks like
strat_White
strat_Black 
strat_Asian # multiple cells have 0
strat_AIAN 
strat_Hispanic 
strat_Unlisted 

array_White <- array(strat_White,
                 dim = c(2,2,4), 
                 list(exposure = c('Yes', 'No'), 
                      outcomes = c('Yes', 'No'), 
                      confounders = 1:4)) 

array_Black <- array(strat_Black,
                 dim = c(2,2,4), 
                 list(exposure = c('Yes', 'No'), 
                      outcomes = c('Yes', 'No'), 
                      confounders = 1:4)) 

array_AIAN <- array(strat_AIAN,
                 dim = c(2,2,4), 
                 list(exposure = c('Yes', 'No'), 
                      outcomes = c('Yes', 'No'), 
                      confounders = 1:4)) 

array_Hispanic <- array(strat_Hispanic,
                 dim = c(2,2,4), 
                 list(exposure = c('Yes', 'No'), 
                      outcomes = c('Yes', 'No'), 
                      confounders = 1:4)) 

array_Unlisted <- array(strat_Black,
                 dim = c(2,2,4), 
                 list(exposure = c('Yes', 'No'), 
                      outcomes = c('Yes', 'No'), 
                      confounders = 1:4)) 

epi.2by2(array_White, method = 'cross.sectional')
epi.2by2(array_Black, method = 'cross.sectional')
epi.2by2(array_AIAN, method = 'cross.sectional')
epi.2by2(array_Hispanic, method = 'cross.sectional')
epi.2by2(array_Unlisted, method = 'cross.sectional')

```
